// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5v-TaB0mxTlOPee2AHU8xHQMeEMG1LI',
    appId: '1:790393020505:web:db14a1bc22f0c16f0b9148',
    messagingSenderId: '790393020505',
    projectId: 'pocketqa-test',
    authDomain: 'pocketqa-test.firebaseapp.com',
    storageBucket: 'pocketqa-test.firebasestorage.app',
    measurementId: 'G-H9BC7FRH11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw3FfgnL0FoTo3-zn1Jn9PgGlacggloXI',
    appId: '1:790393020505:android:bca50ce31cd57cac0b9148',
    messagingSenderId: '790393020505',
    projectId: 'pocketqa-test',
    storageBucket: 'pocketqa-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIVrWZOcvHso5oufPtpUzxLp8E6Pih5pw',
    appId: '1:790393020505:ios:1039c368c42c23160b9148',
    messagingSenderId: '790393020505',
    projectId: 'pocketqa-test',
    storageBucket: 'pocketqa-test.firebasestorage.app',
    iosBundleId: 'com.pocketqa.pocketqa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIVrWZOcvHso5oufPtpUzxLp8E6Pih5pw',
    appId: '1:790393020505:ios:1039c368c42c23160b9148',
    messagingSenderId: '790393020505',
    projectId: 'pocketqa-test',
    storageBucket: 'pocketqa-test.firebasestorage.app',
    iosBundleId: 'com.pocketqa.pocketqa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk5v-TaB0mxTlOPee2AHU8xHQMeEMG1LI',
    appId: '1:790393020505:web:f891545f3a715ac20b9148',
    messagingSenderId: '790393020505',
    projectId: 'pocketqa-test',
    authDomain: 'pocketqa-test.firebaseapp.com',
    storageBucket: 'pocketqa-test.firebasestorage.app',
    measurementId: 'G-LGFGMG2EHH',
  );
}
